preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.0.0
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.28.0

libraries:
  com.android.library:
    com.android.library.gradle.plugin:
      version: 8.5.0
  org.jetbrains.kotlin:
    kotlin-gradle-plugin:
      version: 2.0.0
  com.squareup:
    kotlinpoet:
      version: 1.17.0