preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 1.9.22
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.27.0

libraries:
  com.android.library:
    com.android.library.gradle.plugin:
      version: 8.2.2
  org.jetbrains.kotlin:
    kotlin-gradle-plugin:
      version: 1.9.22
  com.squareup:
    kotlinpoet:
      version: 1.16.0