preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.2.10
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.34.0

libraries:
  com.android.library:
    com.android.library.gradle.plugin:
      version: 8.12.1
  org.jetbrains.kotlin:
    kotlin-gradle-plugin:
      version: 2.2.10
  com.squareup:
    kotlinpoet:
      version: 2.2.0